export const arrow = JSON.parse(`{
    ":left:": "←",
    ":up:": "↑",
    ":right:": "→",
    ":down:": "↓",
    ":left-right:": "↔",
    ":up-down:": "↕",
    ":up-left:": "↖",
    ":up-right:": "↗",
    ":down-right:": "↘",
    ":down-left:": "↙",
    ":double_left:": "⇐",
    ":double_up:": "⇑",
    ":double_right:": "⇒",
    ":double_down:": "⇓",
    ":double_left-right:": "⇔",
    ":double_up-down:": "⇕",
    ":dotted_left:": "⇠",
    ":dotted_up:": "⇡",
    ":dotted_right:": "⇢",
    ":dotted_down:": "⇣",
}`);